name: fairness-oriented-interpretability-of-predictive-algorithms
dependencies:
    - python=3.8
    - notebook
    - numpy
    - pandas
    - pytorch
    - scikit-learn
    - matplotlib
    - seaborn
    - pip
    - pip:
        - plotnine
        - "--editable ."